### ISSUE TITLE
Popup is not visible. 

### ISSUE THREAD

**Issue by denis-trofimov** [arunpkqt/UserLoginApp#2]
In the debugger of Qt Creator 4.3.1
Qt 5.9.0 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)
`QMetaProperty::read: Unable to handle unregistered datatype 'const QQuickPointerDevice*' for property 'QQuickPointerEvent::device'`
Every time the popup is supposed to open.

**Comment by arunpkio** [comment]
@denis-trofimov Thanks for notifying the issue.
I haven't got time to compile this application against Qt 5.9.
I have done a quick search and found that there is some changes happened in Qt5.8 as they have introduced a new internal class.

> Cleaned up touch and mouse event delivery, and added a new internal class QQuickPointerEvent for this purpose.

I guess may be because of this change the issue popped up. Anyway I will try to download Qt5.9 and try to reproduce the issue.In the meantime if you could find some information regarding this please share it.

**Comment by denis-trofimov** [comment]
This warning appears only then I open properties in debug view.
`QMetaProperty::read: Unable to handle unregistered datatype 'const QQuickPointerDevice*' for property 'QQuickPointerEvent::device'`

QQuickPointerEvent::device is undefined pointer const QQuickPointerDevice*


```
